#!/usr/bin/env php
<?php
/* (c) Anton Medvedev <anton@medv.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__ . '/../vendor/autoload.php';

use Deployer\Support\Changelog\Parser;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Style\SymfonyStyle;

chdir(realpath(__DIR__ . '/..'));

$input = new ArgvInput();
$output = new ConsoleOutput();
$app = new Application('Changelog', '1.0.0');
$io = new SymfonyStyle($input, $output);

$app->setDefaultCommand('update');
$app->register('update')->setCode(function () {
    $input = file_get_contents('CHANGELOG.md');

    $parser = new Parser($input);

    $changelog = $parser->parse();

    print_r($changelog);
});

$app->run($input, $output);
